apiVersion: v1
kind: ConfigMap
metadata:
  name: opsdesk-config
  namespace: opsdesk
data:
  APP_NAME: "opsdesk"
  APP_ENV: "kubernetes"
  APP_PORT: "8000"
  DEBUG: "false"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "opsdesk"
  DATABASE_USER: "opsdesk"
  DATABASE_POOL_SIZE: "5"
  DATABASE_MAX_OVERFLOW: "10"
  BACKGROUND_JOB_INTERVAL_SECONDS: "60"
  CORS_ORIGINS: "*"
